"""add new column

Revision ID: 1b6723218a45
Revises: 4af9d020a5a7
Create Date: 2026-01-07 14:15:38.270010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b6723218a45'
down_revision: Union[str, Sequence[str], None] = '4af9d020a5a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchangers', sa.Column('workers', sa.String(length=35), nullable=True))
    op.execute("UPDATE exchangers SET workers = 'Никитос' WHERE workers IS NULL")

    # Делаем NOT NULL
    op.alter_column('exchangers', 'workers', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchangers', 'workers')
    # ### end Alembic commands ###
