"""create users table

Revision ID: 5f33b1c30948
Revises: 1b6723218a45
Create Date: 2026-01-08 04:43:57.902042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f33b1c30948'
down_revision: Union[str, Sequence[str], None] = '1b6723218a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('is_admin', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exchangers', 'workers',
               existing_type=sa.VARCHAR(length=35),
               nullable=False)
    # ### end Alembic commands ###
